### PR TITLE
Clean up merge script

### PR DESCRIPTION
**Pull request by ISSOtm**
Not tested yet, though.

—
This pull request is free and unencumbered software released into the public domain, under the same Unlicense as libplum.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
Thanks! Does it generate the same files? (`make basefiles` will output only the .c and .h, if you want to avoid the overhead of compiling them.)
Also, mind adding a copyright disclaimer here in the pull, for bookkeeping? (See #1 for an example.) Thanks!

**Comment by ISSOtm** [comment]
I should've kept the logic.

**Comment by ISSOtm** [comment]
Done.

**Comment by aaaaaa123456789** [comment]
[00:02] Drush: I wouldn't bother, copyright assignment matters little when the result is public domain :P
[00:02] Drush: You can commit those in yourself, consider this my copyright waiver

(2022-04-03, UTC - 3 timestamps)

**Comment by aaaaaa123456789** [comment]
Merged into `develop`.

**Pull request closed without merging**
